defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: yasser
  password: rsi1111
  pool: 5
  host: mysql


test: &test
  <<: *defaults
  database: timestack

development:
  <<: *defaults
  database: timestack

production:
  <<: *defaults
  database: timestack

cucumber:
  <<: *test
