defaults: &defaults
  adapter: mysql2
  encoding: utf8
<<<<<<< HEAD
  username: root
  password: rsi1111
=======
  username: sparsha
  password: root
>>>>>>> 4d4218ae641147311dcab58c902c872e54742267
  pool: 5
  host: localhost


test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: timestack_development_2


cucumber:
  <<: *test
