defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: sparsha
  password: root
  pool: 5
  host: localhost


test: &test
  <<: *defaults
  database: timestack_test

development:
  <<: *defaults
  database: timestack_development_2


cucumber:
  <<: *test
